API Route: Driver registration
malivinayak/Trip-Management-System pull request #16
Opened 2022-11-16 07:22 UTC by malivinayak

API Route for Driver Registartion
resolves #18

2022-11-16 11:32 UTC, OutdatedGuy approved these changes
~~LGTM!~~

2022-11-16 11:46 UTC, OutdatedGuy requested changes

2022-11-16 11:46 UTC, OutdatedGuy commented on src/backend/routes/registration/driverRegistration.js
> +            query = `select Aadhar_Number from EMPLOYEE where Aadhar_Number = :1`;
Is field name not case-sensitive? At Line 119 we are using all caps name.

2022-11-16 12:55 UTC, malivinayak commented
resolves #18

2022-11-16 15:51 UTC, OutdatedGuy commented
Also change `dbo` variable name to `birthDate`

2022-11-16 17:10 UTC, OutdatedGuy requested changes

2022-11-16 17:10 UTC, OutdatedGuy commented on src/backend/routes/registration/driverRegistration.js
> +            query = `select AADHAR_NUMBER from EMPLOYEE where Aadhar_Number = :1`;
Capitalize the second aadhar_number too.

2022-11-16 17:10 UTC, OutdatedGuy commented on src/backend/routes/registration/driverRegistration.js
> +                    message: "Aadhar_Number is already registered!!!\nYou can either Register with different Aadhar_Number",
Don't send `Aadhar_Number` to frontend, do `Aadhar Number`. And remove `You can either Register with different Aadhar_Number` as it doesn't make any sense

2022-11-16 17:10 UTC, OutdatedGuy commented on src/backend/routes/registration/driverRegistration.js
>              query = `select Lincence_Number from EMPLOYEE where Lincence_Number = :1`;
Capitalize the database fields

2022-11-18 09:45 UTC, OutdatedGuy approved these changes
LGTM!

2022-11-18 09:45 UTC, merged