Added all API Routes
malivinayak/Trip-Management-System pull request #36
Opened 2022-11-17 17:33 UTC by malivinayak

## API ROUTES

1. registration APIs
2. login APIs
3. session-end APIs
4. credentials APIs
5. admin query APIs
6. trip APIs
7. Wallet API's

Closes #34

2022-11-17 19:39 UTC, OutdatedGuy requested changes

2022-11-17 19:39 UTC, OutdatedGuy commented on src/index.js
> +app.post("/api/wallet/withdrawMoney", withdrawMoney);
And new line at end

2022-11-17 19:39 UTC, OutdatedGuy commented on src/index.js
> +import { withdrawMoney } from "./backend/routes/wallet/withdrawMoney.js";
Added newline between different sections

2022-11-18 00:59 UTC, malivinayak commented
I have [added new line at the end](https://github.com/malivinayak/Trip-Management-System/pull/36/commits/9c95f6a796678eb10864bb2c88b09b570a4c0ee6) in this commit
but it is not showing here
![image](https://user-images.githubusercontent.com/66154908/202592227-4a3bcc96-6fa4-4ad2-9c19-3051664f3f12.png)

2022-11-18 09:48 UTC, OutdatedGuy approved these changes
LGTM!

2022-11-18 09:48 UTC, OutdatedGuy commented
> I have [added new line at the end](https://github.com/malivinayak/Trip-Management-System/pull/36/commits/9c95f6a796678eb10864bb2c88b09b570a4c0ee6) in this commit but it is not showing here ![image](https://user-images.githubusercontent.com/66154908/202592227-4a3bcc96-6fa4-4ad2-9c19-3051664f3f12.png)

If at the end it shows this symbol 
<img width="40" alt="image" src="https://user-images.githubusercontent.com/74326345/202672499-6a569580-62be-45cb-8b2c-20c8b63c41a6.png">
 means there not newline.

2022-11-18 09:49 UTC, merged

2022-11-19 01:29 UTC, malivinayak commented
> > I have [added new line at the end](https://github.com/malivinayak/Trip-Management-System/pull/36/commits/9c95f6a796678eb10864bb2c88b09b570a4c0ee6) in this commit but it is not showing here ![image](https://user-images.githubusercontent.com/66154908/202592227-4a3bcc96-6fa4-4ad2-9c19-3051664f3f12.png)
> 
> If at the end it shows this symbol <img alt="image" width="40" src="https://user-images.githubusercontent.com/74326345/202672499-6a569580-62be-45cb-8b2c-20c8b63c41a6.png"> means there not newline.

Got IT