Doc: uploaded documentation files
malivinayak/Trip-Management-System pull request #41
Opened 2022-11-18 06:54 UTC by patilprthm

Following documents are uploaded 
1. SRS

Closes #32

2022-11-18 06:56 UTC, malivinayak commented
@OutdatedGuy Please check changed files as multiple files are reflecting change due to rebase with dev

2022-11-18 06:57 UTC, malivinayak reviewed
SRS is appropriate

2022-11-18 09:52 UTC, OutdatedGuy submitted a review, later dismissed
Great 👍🏼

2022-11-19 01:35 UTC, malivinayak requested changes
@Pratham1402 Update [README.md](https://github.com/malivinayak/Trip-Management-System/blob/doc/doc/README.md) with hyperlink to directly navigate to SRS and PPT's

Note: Update [README.md](https://github.com/malivinayak/Trip-Management-System/blob/doc/doc/README.md) which is located inside [doc](https://github.com/malivinayak/Trip-Management-System/tree/doc/doc) folder

2022-11-22 01:46 UTC, malivinayak requested changes

2022-11-22 01:46 UTC, malivinayak commented on doc/README.md
> +- [SRS](https://github.com/malivinayak/Trip-Management-System/blob/doc/doc/SRS/Group_06_ADS_PBL_SRS.docx)
.docx file is not visible 
Upload .pdf and give a relative path

2022-11-22 01:46 UTC, malivinayak commented on doc/README.md
> +- [Idea Presentation](https://github.com/malivinayak/Trip-Management-System/blob/doc/doc/Idea%20Presentation/ADS%20PBL%20SRS%20PPT.pdf)
embedding link will consume time and data
Use relative path this is a efficient way
e.g.
```
- [Idea Presentation](./Idea%20Presentation/ADS%20PBL%20SRS%20PPT.pdf)
```

2022-11-22 01:46 UTC, malivinayak commented on doc/README.md
> +## Documentation
can you take any other heading here

2022-11-22 01:47 UTC, malivinayak commented
@Pratham1402 I have requested few changes 
Take a look

2022-11-22 04:31 UTC, patilprthm commented on doc/README.md
> +- [SRS](https://github.com/malivinayak/Trip-Management-System/blob/doc/doc/SRS/Group_06_ADS_PBL_SRS.docx)
Done!

2022-11-22 04:32 UTC, patilprthm commented on doc/README.md
> +- [SRS](https://github.com/malivinayak/Trip-Management-System/blob/doc/doc/SRS/Group_06_ADS_PBL_SRS.pdf)
Done!

2022-11-22 04:58 UTC, patilprthm commented on doc/README.md
> +- [Idea Presentation](https://github.com/malivinayak/Trip-Management-System/blob/doc/doc/Idea%20Presentation/ADS%20PBL%20SRS%20PPT.pdf)
Done!

2022-11-22 04:58 UTC, patilprthm commented on doc/README.md
> +## Documentation
Done!

2022-11-22 04:59 UTC, patilprthm commented
> @Pratham1402 I have requested few changes Take a look

2022-11-22 05:01 UTC, patilprthm commented
> > @Pratham1402 I have requested few changes Take a look

Updated the changes. Take a look on it!

2022-11-22 07:17 UTC, malivinayak approved these changes

2022-11-23 01:02 UTC, merged